@startuml

skinparam lineType polyline
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
}

entity Шаблон {
    * id (первичный ключ)
    --
    field (обычное поле)
    - nullable (поле, допускающее значение NULL),
    + field (уникальное поле)
    --
    комментарий
}

entity застройщик {
    * id
    --
    наименование
    + данные_юрлица
    --
    данные застройщика
}

entity строительный_объект {
    * id
    --
    наименование
    адрес
    площадь
    дополнительная_информация
    планируемая_дата_ввода_в_эксплуатацию
    - фактическая дата ввода в эксплуатацию
    --
    данные по строительному объекту
}

entity статус_строительного_объекта {
    * id
    --
    наименование (планируется, строится, задерживается, построен)
    дата перехода в статус
    --
    сущность позволяет отслеживать историю статусов
}

entity покупатель {
    * id
    --
    тип (физическое лицо, юридическое лицо)
    --
    Комментарий
}

entity покупатель_физическое_лицо {
    * id
    --
    ФИО
    Паспортные данные
    Почтовый адрес
    --
    тип покупателя
}

entity покупатель_юридическое_лицо {
    * id
    --
    + ОГРН
    + данные юридического лица
    Почтовый_адрес
    --
    тип покупателя
}

entity договор {
    * id
    --
    регистрационный номер
    сумма_по_договору
    дополнительная_информация
    --
    Данные договора между застройщиком
    и покупателем
}

entity эскроу_счёт {
    * id
    --
    сумма
    дата_внесения_средств
    дополнительная_информация
    данные счёта покупателя
    данные счёта застройщика
    --
    Эскроу-счёт, на который покупатель
    перечисляет средства
}

entity возврат_средств {
    * id
    --
    дата
    --
    Фиксация факта возврата средств
}

entity перевод_средств {
    * id
    --
    дата
      --
    Фиксация факта перевода средств
}

entity статус_договора {
    * id
    --
    наименование (активен, исполнен, выпонен возврат)
    дата перехода в статус
    --
    сущность позволяет отслеживать историю статусов
}

застройщик ||---o{ строительный_объект : 'строит'
строительный_объект ||---o{ статус_строительного_объекта : 'имеет'

застройщик ||---o{ договор : 'заключает'
покупатель ||---o{ договор : 'заключает'
договор |o---|| строительный_объект : 'относится к'
покупатель ||---o{ эскроу_счёт : 'вносит средства'
эскроу_счёт ||---|| договор : 'относится к'
покупатель ||---|| покупатель_физическое_лицо : 'является'
покупатель ||---|| покупатель_юридическое_лицо : 'является'
договор ||---o| перевод_средств : ''
договор ||---o| возврат_средств : ''
договор ||---o{ статус_договора : ''

@enduml